project:
  type: website
  output-dir: docs

website:
  title: "seong-jae's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: projects
      - href: datas.qmd
        text: Patents Datas

  page-footer: "Copyright 2025, LEE SEONG JAE"

format:
  html:
    theme:
      - lux
      - balenciaga-theme.scss
    css: styles.css
    toc: true
